2025-01-17 20:07:44,144 - ERROR - XML parse error: syntax error: line 1, column 0
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 332, in analyze_tests
    tree = ET.parse(filename)
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2025-01-17 20:09:35,633 - ERROR - XML parse error: syntax error: line 1, column 0
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 332, in analyze_tests
    tree = ET.parse(filename)
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2025-01-17 20:10:18,423 - ERROR - XML parse error: syntax error: line 1, column 0
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 332, in analyze_tests
    tree = ET.parse(filename)
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\gueas\AppData\Local\Programs\Python\Python313\Lib\xml\etree\ElementTree.py", line 569, in parse
    self._root = parser._parse_whole(source)
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
2025-01-17 20:14:53,656 - INFO - File content preview: log
"2025-01-09 19:10:55.809 ERROR [grog-batch-export,,] 1 --- [cTaskExecutor-8] e.t.g.b.v.d.VigilanzaOperationCreator    : Mcc beneficiario. Reference IT71H3692801600000000102145 operationReference 4
2025-01-17 20:16:58,999 - INFO - File content preview: log
"2024-12-09 09:09:02.275  INFO [grog-ms,,] 1 --- [ntainer#5-0-C-1] e.t.grog.monitor.kafka.KafkaListeners    : ----- New message on ""sctPaymentInfoTopic"": ConsumerRecord(topic = SCT_paymentInfo, 
2025-01-17 20:18:02,676 - INFO - File content preview: log
"2024-12-09 09:09:02.275  INFO [grog-ms,,] 1 --- [ntainer#5-0-C-1] e.t.grog.monitor.kafka.KafkaListeners    : ----- New message on ""sctPaymentInfoTopic"": ConsumerRecord(topic = SCT_paymentInfo, 
2025-01-17 20:30:49,154 - INFO - File content preview: log
"2024-12-09 09:09:02.275  INFO [grog-ms,,] 1 --- [ntainer#5-0-C-1] e.t.grog.monitor.kafka.KafkaListeners    : ----- New message on ""sctPaymentInfoTopic"": ConsumerRecord(topic = SCT_paymentInfo, 
2025-01-17 20:30:49,158 - ERROR - Analysis error: 'TestAnalyzerGUI' object has no attribute '_update_interface'
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 353, in analyze_tests
    self._analyze_text(content)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 407, in _analyze_text
    self._update_interface()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestAnalyzerGUI' object has no attribute '_update_interface'
2025-01-17 20:34:42,013 - INFO - File content preview: log
"2024-12-09 09:09:02.275  INFO [grog-ms,,] 1 --- [ntainer#5-0-C-1] e.t.grog.monitor.kafka.KafkaListeners    : ----- New message on ""sctPaymentInfoTopic"": ConsumerRecord(topic = SCT_paymentInfo, 
2025-01-17 20:34:42,016 - ERROR - Analysis error: 'TestAnalyzerGUI' object has no attribute '_update_interface'
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 353, in analyze_tests
    self._analyze_text(content)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\TestReportGenerator.py", line 407, in _analyze_text
    self._update_interface()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestAnalyzerGUI' object has no attribute '_update_interface'
2025-01-17 20:41:02,005 - INFO - File content preview: log
"2024-12-09 09:09:02.275  INFO [grog-ms,,] 1 --- [ntainer#5-0-C-1] e.t.grog.monitor.kafka.KafkaListeners    : ----- New message on ""sctPaymentInfoTopic"": ConsumerRecord(topic = SCT_paymentInfo, 
2025-01-17 21:28:57,126 - ERROR - Analysis error: 'TestAnalyzerTab' object has no attribute '_update_summary'
Traceback (most recent call last):
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\test_analyzer_tab.py", line 193, in analyze_file
    self.update_results_display()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gueas\PycharmProjects\AnalysprojectSG\src\test_analyzer_tab.py", line 386, in update_results_display
    self._update_summary()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TestAnalyzerTab' object has no attribute '_update_summary'
